config/routes.rb
Rails.application.routes.draw do
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  get 'bloghome/index'

  resources :blogposts do
    resources :comments
  end

  resources :comments

  root :to => 'bloghome#index', :as => 'bloghome'

end

app/models/blogpost.rb
class TimeValidator < ActiveModel::Validator
  def validate(record)
    @d = DateTime.now
    @dn = @d + Rational('0.05')
    if record.date_posted < @d
      record.errors[:base] << "Time must be after current time"
    else if record.date_posted > @dn
      record.errors[:base] << "Time must be within 1 hours of current time"
      end
    end
  end
end


class Blogpost < ActiveRecord::Base
  validates_with TimeValidator

  validates :title, :blog, :creator, presence: true

  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png|jpeg)\Z}i,
    message: 'must be a URL for GIF, JPG, JPEG or PNG image.'
  }
  
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blogpost
  belongs_to :user
  validates :content, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bloghome_controller.rb
class BloghomeController < ApplicationController
  def index
    @blogposts = Blogpost.order(date_posted: :desc)
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  # GET /blogposts
  # GET /blogposts.json
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :image_url, :blog, :date_posted, :creator)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    if session[:user_id]
      user = User.find_by(id: params[session[:user_id]])
    end
    @blogpost = Blogpost.find(params[:blogpost_id])
    if user
      @comment = @blogpost.comments.create(params[:content].merge(user: user))
    else
      @comment = @blogpost.comments.create(comment_params)
    end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blogpost_path(@blogpost), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :blogpost_id, :user_id, :sock)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
      if user and user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to bloghome_url
      else
        redirect_to login_url, alert: "Invalid user/password combination"
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to store_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "#{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloghome_helper.rb
module BloghomeHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bloghome/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Blog</h1>

<% @blogposts.each do |blogpost| %>
  <div class="entry">
    <h2><%= blogpost.title %></h2>
    <h4>by <%= blogpost.creator %></h4>
    <!--<%= image_tag(blogpost.image_url) %>-->
    <%= sanitize blogpost.blog %>
    <div class="date_posted_line">
      <div class = "date_posted">
        <%= blogpost.date_posted %>
      </div> <br/>
      <%= blogpost.comments.count %> 
      <%= link_to 'Comments', blogpost %>
    </div>

  </div>
<% end %>

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :blog %><br>
    <%= f.text_area :blog %>
  </div>
  <div class="field">
    <%= f.label :date_posted %><br>
    <%= f.datetime_select :date_posted %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/edit.html.erb
<h1>Editing Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogposts</h1>

<table>

  <tbody>
    <% @blogposts.each do |blogpost| %>
      
      <%= content_tag :tr, class: cycle('list_line_odd', 'list_line_even') do %>
          <td class='lcol'>
          </td>
          <td>
          <table>
          <tr class ='list_title'>
            <td>
            <dl>          
            <dt><%= blogpost.title %></dt>
            </dl>
            </td>
            <td>
            <dl><%= blogpost.date_posted %></dl>
            </td>
            
          </tr>
          <tr class ='list_blog'>
            <td>
            <dl>
            <dt><%= blogpost.creator %></dt>
            <dd><%=truncate blogpost.blog, length: 500 %></dd>
            </dl>
            </td>
          </tr>
          <tr>
            <td>
            <dl><%= image_tag(blogpost.image_url, class: 'list_image') %></dl>
            </td>
          </tr>
          <tr class ='list_actions'>
            <td>
            <%= link_to 'Show', blogpost %><br/>
            <%= link_to 'Edit', edit_blogpost_path(blogpost) %><br/>
            <%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
          </table>
          </td>
      
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogpost', new_blogpost_path %>

app/views/blogposts/new.html.erb
<h1>New Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

app/views/blogposts/show.html.erb
<center>
<p>
  <big>
  <strong>
    <%= @blogpost.title %>
  </strong>
  </big>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @blogpost.creator %>
</p>

<p>
  <strong>Date:</strong>
  <%= @blogpost.date_posted %>
</p>

<p>
  <%= image_tag(@blogpost.image_url, height: "350", width: "400") %>
</p>

<p>
  <%= @blogpost.blog %>
</p>

<h2>Comments</h2>
<% @blogpost.comments.each do |comment| %>
  <p>
  <table>
  <tbody>
    <tr class='comment_background'>
    <td class='comment'>
    <dl><dt><%= comment.content %></dl></dt>
    by <%= comment.user %> at <%= comment.created_at %>
    </td>
    </tr>
  </tbody>
  </table>
  </p>
<% end %>


<h2>Add a comment:</h2>
<%= render "comments/form" %>


<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', bloghome_path %>

</center

app/views/comments/_comment.html.erb
<h2>Recent Comments</h2>
<table>
  <% @comments.each do |comment| %>
  <p>
    <%= comment.content %><br/>
    <%= comment.created_at %>
  </p>
  <% end %>

</table>

app/views/comments/_form.html.erb
<%= form_for([@blogpost, @blogpost.comments.build]) do |f| %>
  

     

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Blogpost</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.blogpost %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Blogpost:</strong>
  <%= @comment.blogpost %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<%= content_tag :body, class: controller.controller_name do %>
<div id="columns">
  <div id="side">
    <ul>
	<li><a href="http://www....">Home</a></li>
	<li><a href="http://www..../faq">Questions</a></li>
	<li><a href="http://www..../news">News</a></li>
	<li><a href="http://www..../contact">Contact</a></li>
        <%= Time.now %>
    </ul>
      
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
<% end %>

</html>

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div class="field">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, size: 40 %>
  </div>


  <div class="field">
    <%= f.label :password_confirmation, 'Confirm:' %>
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>